version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - WEATHER_API_KEY=${WEATHER_API_KEY}
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend